tools/KEP_Tools/crashfix-code/crashfix_webapp/protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	public $sidebarActiveItem = 'Administer';
	
	public $adminMenuItem='Users';
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(			
			array('allow', 
				'actions'=>array('view'),
				'users'=>array('@'),
			),
			array('allow', 
				'actions'=>array('index', 'create', 'update', 'retire', 'resurrect', 'delete', 'addProjectRole', 'deleteProjectRoles'),
				'roles'=>array('gperm_access_admin_panel'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		// Allow admin to view all profiles and
		// allow user to view his own profile.
		if( !Yii::app()->user->checkAccess('gperm_access_admin_panel') &&
		    !Yii::app()->user->checkAccess('gperm_view_own_profile', array('user_id'=>$id)) )
		{
			throw new CHttpException(403, 'You are not authorized to perform this action.');
		}
		
		$userProjectAccess = new UserProjectAccess;
		$userProjectAccess->user_id = $id;
		
		if(!Yii::app()->user->checkAccess('gperm_access_admin_panel'))			
			$this->adminMenuItem=null;
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'userProjectAccess'=>$userProjectAccess
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User('create');
		$model->usergroup = 4;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);		
		if(isset($_POST['User']))
		{	
			$model->attributes=$_POST['User'];			
			if($model->save())
			{
				if($model->sendEmailWithAccountActivationLink())
				{
					Yii::app()->user->setFlash('success', 
						'The new user has been added successfully. An E-mail message with account activation link has been sent to new user\'s mailbox.');
				}
				else
				{
					Yii::app()->user->setFlash('error', 'The new user has been added. However an E-mail message with account activation link couldn\'t be sent to new user\'s mailbox. Please check your SMTP server.');
				}
				
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.	 
	 */
	public function actionUpdate()
	{
		if(!isset($_POST['id']))
			throw new CHttpException(400, 'Invalid request');
		
		$id = $_POST['id'];
		
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Marks a particular model as retired (inactive).
	 */
	public function actionRetire()
	{
		// We only allow this via POST request		
		if(Yii::app()->request->isPostRequest && isset($_POST['id']))
		{			
			// Get user ID 
			$id = $_POST['id'];			
			
			// Make changes in AR
			$this->loadModel($id)->retire();

			// Redirect to index action
			$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400, 'Invalid request.');
	}
	
	/**
	 * Marks a particular retired model as active.
	 */
	public function actionResurrect()
	{
		// We only allow this via POST request		
		if(Yii::app()->request->isPostRequest && isset($_POST['id']))
		{			
			// Get user ID 
			$id = $_POST['id'];			
			
			// Make changes in AR
			$user = $this->loadModel($id);
			
			// Check if user is a real retired.
			if($user->status!=User::STATUS_DISABLED)
				throw new CHttpException(400, 'Invalid request.');
			
			$user->resurrect();

			// Redirect to index action
			$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400, 'Invalid request.');
	}
	
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.	 
	 */
	public function actionDelete()
	{
		// We only allow deletion via POST request
		if(Yii::app()->request->isPostRequest && isset($_POST['id']))
		{			
			// Get user ID to delete
			$id = $_POST['id'];			
			
			$this->loadModel($id)->delete();

			$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400, 'Invalid request.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		// Create search form
		$model = new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_POST['User']))
			$model->attributes = $_POST['User'];
		
		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Adds a project role for user.
	 */
	public function actionAddProjectRole()
	{
		if(!isset($_POST['id']))
            throw new CHttpException(403, 'Invalid request');
		
        $userId = $_POST['id'];
        
        $user = User::model()->findByPk($userId);
        if($user===Null)
            throw new CHttpException(403, 'Invalid request');
        
		if(isset($_POST['Project']))
		{   
            // Get items
            $items = $_POST['Project'];
            
            // Get values of checkbox column
            $checks = array();
            if(isset($_POST['check']))
                $checks = $_POST['check'];
            
            // Walk through items
            foreach($items as $projectId=>$item)
            {
                // Find user project access record 
                $model = UserProjectAccess::model()->findByAttributes(
                        array('user_id'=>$userId,
                            'project_id'=>$projectId));
                
                // Find out if this item is checked or not
                if(in_array($projectId, $checks)) // checked
                {
                    if($model===Null) // If this user has no access to this project...
                    {
                        // Give him access
                        $model = new UserProjectAccess();
                        $model->user_id = $userId;
                        $model->project_id = $projectId;
                        $model->usergroup_id = $item['role'];

                        if(!$model->save())
                            throw new CHttpException(403, 'Error saving record to database');				                
                    }
                }
                else // unchecked
                {
                    if($model!=Null) // If user has access to project
                    {
                        // Revoke access
                        if(!$model->delete())
                            throw new CHttpException(403, 'Error deleting record from database');				                
                    }
                }
			}
            
            Yii::app()->user->setFlash(
                            'success', 
                            'User roles have been updated.'
                            );
                    
            $this->redirect(array('user/view', 'id'=>$userId));					
            return;
		}
        
        $criteria=new CDbCriteria;                

        $dataProvider =  new CActiveDataProvider('Project', array(
            'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>'name ASC'
            ),
            'pagination'=>false
        ));
        
        $this->render('addProjectRole',array(
            'user'=>$user,
            'dataProvider'=>$dataProvider
        ));      
	}
	
	/**
	 * Deletes one or several project roles from user.	 
	 */	
	public function actionDeleteProjectRoles()
	{		
		if(!isset($_POST['DeleteRows']) || !isset($_POST['user_id']))
		{
			throw new CHttpException(404, 'The parameter is invalid');
		}
				
		// Get data from user
		$deleteRows=$_POST['DeleteRows'];
		$userId = $_POST['user_id'];
		
		foreach($deleteRows as $id)
		{
			$model = UserProjectAccess::model()->findByPk($id);
			if($model===Null)
				throw new CHttpException(404, 'The specified record doesn\'t exist in the database.');
				
			// Delete row from database table and remove file attachment
			if(!$model->delete())
			{
				throw new CHttpException(404, 'The specified record doesn\'t exist in the database or could not be deleted.');
			}
		}
		
        Yii::app()->user->setFlash(
                            'success', 
                            'User roles have been updated.'
                            );
        
		// Redirect to index
		$this->redirect(array('user/view', 'id'=>$userId));
	}
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}	
}

tools/KEP_Tools/crashfix-code/crashfix_webapp/protected/views/user/addProjectRole.php
<?php
$this->breadcrumbs=array(
	'Administer'=>array('site/admin'), 
	'Users',
	CHtml::encode($user->username),
	'Add Project Roles'
);

?>

<div class="span-18 last">

    <div class="form">

    <div class="hint">
        Check the boxes next to the names of projects in which the user must 
        participate, and then click the Save button to apply your changes.
    </div>


    <?php $form=$this->beginWidget('CActiveForm', array(
        'id'=>'add-project-role-form',
        'enableAjaxValidation'=>false,
    )); ?>

    <?php echo CHtml::hiddenField('id', $user->id); ?>

    <!-- Grid view -->
    <div class="span-18 last">
    <?php     

        $models = UserGroup::model()->findAll(); 
        $list = CHtml::listData($models, 'id', 'name');

        $this->widget('zii.widgets.grid.CGridView', array(
        'dataProvider'=>$dataProvider,
        'selectableRows'=>null,
        'summaryText'=>'',
        'columns'=>array(		            
            array(                          
                'class'=>'CCheckBoxColumn',			  			  
                'id'=>'check',
                'selectableRows'=>2, // allow multiple rows to select                            
                'checked'=> function($data,$row) use ($user) {return $user->isInProject($data->id);}
            ),
            array(     
                'header'=>'Project Name',
                'name'=>'name',
                'type' => 'raw',			  
                'value' =>'CHtml::link($data->name, array(\'project/view\', \'id\'=>$data->id))',	  			  			  
            ),	
            array(     			  
                'header'=>'Role',
                'type'=>'raw',              
                'value'=>function($data,$row) use ($user, $list){ return CHtml::dropDownList("Project[".$data->id."][role]", array('selected'=>$user->suggestProjectRole($data->id)), $list); },              
                ),
        ),
    )); 
    ?>

    <?php $this->endWidget(); ?>

    <div class="row">
    <?php echo CHtml::submitButton('Save'); ?>
    </div>

    </div>
    
</div>

tools/KEP_Tools/crashfix-code/crashfix_webapp/protected/views/user/create.php
<h3>Add New User</h3>

<div class="form wide">

	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>'user-form',
		'enableAjaxValidation'=>false,
	)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>
		
	<div class="row">
	<?php echo $form->labelEx($model,'usergroup'); ?>
	<?php 		
		$models = UserGroup::model()->findAll(); 
        $list = CHtml::listData($models, 'id', 'name');
		echo CHtml::dropDownList('User[usergroup]', array('selected'=>$model->usergroup), $list); 
	?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

tools/KEP_Tools/crashfix-code/crashfix_webapp/protected/views/user/index.php
<?php
$this->breadcrumbs=array(
	'Administer', 
	'Users',

);

?>

<!-- Simple Search Form -->
<div class="span-18 last" id="div_simple_search">
	<?php echo CHtml::beginForm(Yii::app()->createUrl($this->route), 'post'); ?>
	<div class="span-18 last"><p id="stat_filter">Search by user name/E-mail address:</p></div>
	<div class="span-4"><div id="dropdown_search">
		<?php 
			$user_statuses = array(												
				 1=>'Active users',
				 2=>'Disabled users',
				-1=>'All users',
			);			
			echo CHtml::dropDownList('User[status]', array('selected'=>isset($model->status)?CHtml::encode($model->status):1), $user_statuses); 
		?></div>
	</div>
	<div class="span-11">
		<?php echo CHtml::textField('User[username]', isset($model->username) ? CHtml::encode($model->username):"", array('id'=>'text_filter')); ?>
	</div>
	<div class="span-2 last">
		<?php echo CHtml::submitButton('Search', array('id'=>'btn_filter')); ?>
	</div>
	<?php echo CHtml::endForm(); ?>
</div>

<!-- Actions Toolbar -->
<div class="span-18 last">
	<div class="div_actions">
		<?php echo CHtml::link('Add New User', $this->createUrl('user/create')); ?>		
	</div>	
</div>

<!-- Grid view -->
<div class="span-18 last">
<?php $this->widget('zii.widgets.grid.CGridView', array(
      'dataProvider'=>$model->search(),
	  'selectableRows'=>null,
      'columns'=>array(		  
          'id',             
          array(            
              'name' => 'username',
			  'type' => 'raw',
			  'value' => 'CHtml::link($data->username, \'view/\'.$data->id)',	  			  			  
          ),		  
		  array(
			  'header'=>'Group',			  
              'name'=>'usergroup',
			  'type' => 'raw',
              'value'=>'CHtml::link($data->group->name, array(\'userGroup/view/\', \'id\'=>$data->usergroup))',	  			  			  
          ),
		  array(
			  'header'=>'Status',			  
              'name'=>'status',
              'value'=>'$data->getEffectiveStatusStr()',
          ),		  		  
		  'email',       
      ),
 )); 
  
 ?>
</div>

tools/KEP_Tools/crashfix-code/crashfix_webapp/protected/views/user/update.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	CHtml::encode($model->username)=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'View User', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<div class="form wide">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<?php echo CHtml::hiddenField('id', $model->id); ?>
	
	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo CHtml::encode($model->username); ?>		
	</div>
		
	<div class="row">
	<?php echo $form->label($model,'usergroup'); ?>
	<?php 
		if(!$model->isStandard())
		{
			$models = UserGroup::model()->findAll(); 
			$list = CHtml::listData($models, 'id', 'name');
			echo CHtml::dropDownList('User[usergroup]', array('selected'=>$model->usergroup), $list); 
		}
		else
		{
			echo CHtml::encode($model->group->name);
		}
	?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

tools/KEP_Tools/crashfix-code/crashfix_webapp/protected/views/user/view.php
<?php

if(Yii::app()->user->checkAccess('gperm_access_admin_panel'))
{
	$this->breadcrumbs=array(
		'Administer', 
		'Users'=>array('user/index'),
		CHtml::encode($model->username));
}
else
{
	$this->breadcrumbs=array(		
		'Users',
		CHtml::encode($model->username));
}

?>

<!-- Flash messages -->
<div class="span-18 last ">
<?php	
    foreach(Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
    }
?>
</div>

<div class="span-18 last ">
	<h4>General Info:</h4>
</div>

<!-- Actions Toolbar -->
<div class="span-18 last">
	<div class="div_actions">
		
			<?php echo CHtml::form(); ?>		
		
			<?php 
				if(Yii::app()->user->getId()==$model->id)
				{
					echo CHtml::linkButton('Change Password', 
						array(
							'submit'=>Yii::app()->createUrl('site/resetPassword'),						
							'confirm'=>"Are you sure you want to change your password?")
						);					
				}
			?>	
		
			<?php echo CHtml::hiddenField('id', $model->id); ?>			
		
			<?php
			
				if(Yii::app()->user->checkAccess('gperm_access_admin_panel'))
				{
			
					echo CHtml::linkButton('Update User', 
								array('submit'=>Yii::app()->createUrl('user/update'))
								);				

					if(!$model->isStandard())
					{

						if($model->getEffectiveStatus()!=User::STATUS_DISABLED) 
						{
							echo CHtml::linkButton('Disable User', 
								array(
									'submit'=>Yii::app()->createUrl('user/retire'),						
									'confirm'=>"Are you sure you want to set status of user ".$model->username." to 'Retired'?")
								);
						}
						else
						{
							echo CHtml::linkButton('Enable User', 
								array(
									'submit'=>Yii::app()->createUrl('user/resurrect'),						
									'confirm'=>"Are you sure you want to set status of user ".$model->username." to 'Active'?")
								);
						}

						echo CHtml::linkButton('Delete User', 
							array(
								'submit'=>Yii::app()->createUrl('user/delete'),						
								'confirm'=>"Are you sure you want to permanently delete user ".$model->username."?")
							); 
					}
				}
			?>	
		
			<?php echo CHtml::endForm(); ?>		
	</div>	
</div>


<!-- Detail View -->
<div class="span-18 last">
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'username',	
        array(  
			'label'=>'User Group',
            'type'=>'raw',
            'value'=>Yii::app()->user->checkAccess('gperm_access_admin_panel')?CHtml::link(CHtml::encode($model->group->name), array('userGroup/view', 'id'=>$model->usergroup)):CHtml::encode($model->group->name),
        ),
		array(  
            'label'=>'Status',
            'type'=>'text',
            'value'=>$model->getEffectiveStatusStr(),
        ),
		'email',
	),
)); ?>
</div>

<!-- Permissions -->
<div class="prepend-top span-18 last">
	<h4>Project Roles:</h4>
</div>

<!-- Actions Toolbar -->
<div class="span-18 last">
	<div class="div_actions">
		
			<?php echo CHtml::form(); ?>		
		
			<?php echo CHtml::hiddenField('id', $model->id); ?>			
		
			<?php	
            if(Yii::app()->user->checkAccess('gperm_access_admin_panel'))
            {
					echo CHtml::linkButton('Add Project Role(s)', 
								array('submit'=>Yii::app()->createUrl('user/addProjectRole'))
								);				
				
				echo CHtml::link("Delete Selected Roles", "#", array('id'=>'delete_selected'));
            }
			?>	
		
			<?php echo CHtml::endForm(); ?>		
	</div>	
</div>

<?php echo CHtml::beginForm(array('user/deleteProjectRoles'), 'post', array('name'=>'del_form')); ?>

<?php echo CHtml::hiddenField('user_id', $model->id); ?>

<!-- Grid view -->
<div class="span-18 last">
<?php $this->widget('zii.widgets.grid.CGridView', array(
      'dataProvider'=>$userProjectAccess->search(),
	  'selectableRows'=>null,
      'columns'=>array(		            
		  array(            
              'class'=>'CCheckBoxColumn',			  			  
			  'id'=>'DeleteRows',
			  'selectableRows'=>2, // allow multiple rows to select
          ),
          array(
			  'header'=>'Project',			  
              'name'=>'project_id',
			  'type' => 'raw',
              'value'=>'Yii::app()->user->checkAccess(\'gperm_access_admin_panel\')?CHtml::link($data->project->name, array(\'project/view/\', \'id\'=>$data->project_id)):CHtml::encode($data->project->name)',	  			  			  
          ),
		  array(
			  'header'=>'Project Role',			  
              'name'=>'usergroup_id',
			  'type' => 'raw',
              'value'=>'Yii::app()->user->checkAccess(\'gperm_access_admin_panel\')?CHtml::link($data->usergroup->name, array(\'userGroup/view/\', \'id\'=>$data->usergroup_id)):CHtml::encode($data->usergroup->name)',	  			  			  
          ),
		  
      ),
 )); 
  
 ?>
</div>

<?php echo CHtml::endForm(); ?>

<?php 
 $script = <<<SCRIPT
$(":checkbox").live('click', function(e)
{		
	var totalSelected = 0;
	$("input[name='DeleteRows\[\]']").each(function() {if($(this).attr('checked')) totalSelected++;});
	
	if(totalSelected==0)
		$("#delete_selected").css('visibility', 'hidden');
	else
		$("#delete_selected").css('visibility', 'visible');
	
});

$("#delete_selected").bind('click', function(e)
{	
	$("[name=del_form]").submit();
});

SCRIPT;
 
 Yii::app()->getClientScript()->registerScript("DebugInfo", $script, CClientScript::POS_READY); ?>